"""init_db_schema

Revision ID: b171dc25c453
Revises: b31b93910e2e
Create Date: 2026-02-06 22:26:54.025790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
import pgvector  # Bunu da şimdiden ekle, birazdan lazım olacak

# revision identifiers, used by Alembic.
revision: str = 'b171dc25c453'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable required PostgreSQL extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('carrier_code', sa.String(length=10), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=True),
    sa.Column('baggage_allowance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flight_tenant_route_date', 'flights', ['tenant_id', 'origin', 'destination', 'departure_time'], unique=False)
    op.create_index(op.f('ix_flights_carrier'), 'flights', ['carrier'], unique=False)
    op.create_index(op.f('ix_flights_departure_time'), 'flights', ['departure_time'], unique=False)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_external_id'), 'flights', ['external_id'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_index(op.f('ix_flights_provider'), 'flights', ['provider'], unique=False)
    op.create_index(op.f('ix_flights_tenant_id'), 'flights', ['tenant_id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('concept', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hotel_embedding_ivfflat', 'hotels', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_hotel_location_gist', 'hotels', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_hotel_tenant_city', 'hotels', ['tenant_id', 'city'], unique=False)
    op.create_index('idx_hotel_tenant_city_price', 'hotels', ['tenant_id', 'city', 'price'], unique=False)
    #op.create_index('idx_hotels_location', 'hotels', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_hotels_area'), 'hotels', ['area'], unique=False)
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_concept'), 'hotels', ['concept'], unique=False)
    op.create_index(op.f('ix_hotels_district'), 'hotels', ['district'], unique=False)
    op.create_index(op.f('ix_hotels_external_id'), 'hotels', ['external_id'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_index(op.f('ix_hotels_provider'), 'hotels', ['provider'], unique=False)
    op.create_index(op.f('ix_hotels_tenant_id'), 'hotels', ['tenant_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('pickup_coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfer_dropoff_gist', 'transfers', ['dropoff_coordinates'], unique=False, postgresql_using='gist')
    op.create_index('idx_transfer_pickup_gist', 'transfers', ['pickup_coordinates'], unique=False, postgresql_using='gist')
    op.create_index('idx_transfer_tenant_locations', 'transfers', ['tenant_id', 'pickup_location', 'dropoff_location'], unique=False)
    #op.create_index('idx_transfers_dropoff_coordinates', 'transfers', ['dropoff_coordinates'], unique=False, postgresql_using='gist')
    #op.create_index('idx_transfers_pickup_coordinates', 'transfers', ['pickup_coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_transfers_dropoff_location'), 'transfers', ['dropoff_location'], unique=False)
    op.create_index(op.f('ix_transfers_external_id'), 'transfers', ['external_id'], unique=False)
    op.create_index(op.f('ix_transfers_pickup_location'), 'transfers', ['pickup_location'], unique=False)
    op.create_index(op.f('ix_transfers_provider'), 'transfers', ['provider'], unique=False)
    op.create_index(op.f('ix_transfers_tenant_id'), 'transfers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transfers_vehicle_type'), 'transfers', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_vehicle_type'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_tenant_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_provider'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_pickup_location'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_external_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_dropoff_location'), table_name='transfers')
    op.drop_index('idx_transfers_pickup_coordinates', table_name='transfers', postgresql_using='gist')
    op.drop_index('idx_transfers_dropoff_coordinates', table_name='transfers', postgresql_using='gist')
    op.drop_index('idx_transfer_tenant_locations', table_name='transfers')
    op.drop_index('idx_transfer_pickup_gist', table_name='transfers', postgresql_using='gist')
    op.drop_index('idx_transfer_dropoff_gist', table_name='transfers', postgresql_using='gist')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_hotels_tenant_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_provider'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_external_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_district'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_concept'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_area'), table_name='hotels')
    op.drop_index('idx_hotels_location', table_name='hotels', postgresql_using='gist')
    op.drop_index('idx_hotel_tenant_city_price', table_name='hotels')
    op.drop_index('idx_hotel_tenant_city', table_name='hotels')
    op.drop_index('idx_hotel_location_gist', table_name='hotels', postgresql_using='gist')
    op.drop_index('idx_hotel_embedding_ivfflat', table_name='hotels', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('hotels')
    op.drop_index(op.f('ix_flights_tenant_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_provider'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_external_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure_time'), table_name='flights')
    op.drop_index(op.f('ix_flights_carrier'), table_name='flights')
    op.drop_index('idx_flight_tenant_route_date', table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
